### ISSUE TITLE
Terminal/Window Size enforcement too eager / not enforced

### ISSUE THREAD

**Issue by Lau-r-a** [xenya52/game_2048#2]
Description: The window size enforcment is too eager and is cutting of parts of the game:
<img width="151" alt="grafik" src="https://github.com/xenya52/game_2048/assets/103428878/511fdde9-5da0-491a-87fa-dc48967d3a88">

Details:
* Plattform: MacOS (M1)
* Terminal: Terminal V2.14

Additional Details: The enforcment seems to not be supported by most terminals anyways

**Comment by xenya52** [comment]
Im in sis
